### ISSUE TITLE
Починить dependabot

### ISSUE THREAD

**Issue by nkiryanov** [fandsdev/django#812]
dependabot не работает, якобы ошибка в файле конфигурации

![Image](https://github.com/user-attachments/assets/17b524bb-bd2f-4ca6-bc7f-e9b614ca5e36)

Файл конфигурации такой:
```yaml
version: 2
updates:
- package-ecosystem: uv   // <-- проблема возникла когда поменял  `pip` → `uv`
  directory: "/{{ cookiecutter.name }}"  // <-- якобы проблема тут, но когда был `package-ecosystem: pip` было норм
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
```

Предполагаю (это не точно) он сходит с ума из-за `{` в названии папки. Нужно проверить и понять как править — можно ли исправить самим, может быть сделать issue в репозитории dependabot-core
